#!/usr/bin/env bash
# scripts/build_for_sm75.sh -- cuda-oxide example を Turing (sm_75) GPU で
# 動かすための workaround スクリプト
#
# cuda-oxide の codegen は --mcpu=sm_80 固定 (公式は Ampere+) のため、
# Turing GPU では PTX JIT load が CUDA_ERROR_INVALID_PTX (218) で失敗する。
# 本スクリプトは:
#   1. cargo oxide build で .ll/.ptx を生成
#   2. .ll を llc-21 --mcpu=sm_75 -mattr=+ptx70 で sm_75 PTX に再 compile
#   3. example の <name>.ptx を上書き
#   4. example binary を直接実行
#
# 適用範囲: LLVM IR に sm_80+ 専用 op (cp.async, wgmma, tcgen05, tma., cluster.)
# が含まれない単純 kernel に限る。Stage 1 KP-abs 程度なら適用可能。
#
# 詳細は docs/setup.md の "sm_75 (Turing) workaround" セクション参照。

set -euo pipefail

EXAMPLE=""
CUDA_OXIDE_DIR="${CUDA_OXIDE_DIR:-$HOME/git-repos/cuda-oxide}"
CARGO_OXIDE_BIN="${CARGO_OXIDE_BIN:-}"
NO_RUN=0
ARCH="${ARCH:-sm_75}"
PTX_FEATURE="${PTX_FEATURE:-+ptx70}"

usage() {
  cat <<EOF
Usage: $0 <example_name> [options]

Run a cuda-oxide example on a sub-Ampere GPU (default sm_75) by post-processing
the LLVM IR through llc-21 with a lower --mcpu and swapping the resulting PTX.

Options:
  --cuda-oxide-dir DIR  Path to cuda-oxide repo (default: \$CUDA_OXIDE_DIR or
                        ~/git-repos/cuda-oxide)
  --cargo-oxide BIN     cargo-oxide binary path. If unset, auto-detected from
                        \$CARGO_OXIDE_BIN, then <cuda-oxide-dir>/target/release,
                        then /mnt/e/cuda-oxide-target/release
  --arch ARCH           Target arch (default: sm_75; try sm_70 for Volta etc)
  --ptx-feature FEAT    llc -mattr value (default: +ptx70)
  --no-run              Build + PTX swap only, skip execution
  -h, --help            Show this help

Env vars: CUDA_OXIDE_DIR, CARGO_OXIDE_BIN, ARCH, PTX_FEATURE
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --cuda-oxide-dir) CUDA_OXIDE_DIR="$2"; shift 2 ;;
    --cargo-oxide)    CARGO_OXIDE_BIN="$2"; shift 2 ;;
    --arch)           ARCH="$2"; shift 2 ;;
    --ptx-feature)    PTX_FEATURE="$2"; shift 2 ;;
    --no-run)         NO_RUN=1; shift ;;
    -h|--help)        usage; exit 0 ;;
    -*)               echo "error: unknown option: $1" >&2; usage >&2; exit 2 ;;
    *)                if [[ -z "$EXAMPLE" ]]; then EXAMPLE="$1"; else
                        echo "error: unexpected positional arg: $1" >&2; exit 2
                      fi; shift ;;
  esac
done

if [[ -z "$EXAMPLE" ]]; then
  echo "error: example name required" >&2
  usage >&2
  exit 2
fi

if [[ ! -d "$CUDA_OXIDE_DIR" ]]; then
  echo "error: cuda-oxide repo not found at $CUDA_OXIDE_DIR" >&2
  echo "  Set CUDA_OXIDE_DIR or use --cuda-oxide-dir" >&2
  exit 2
fi

# Auto-detect cargo-oxide binary
if [[ -z "$CARGO_OXIDE_BIN" ]]; then
  for candidate in \
      "$CUDA_OXIDE_DIR/target/release/cargo-oxide" \
      "/mnt/e/cuda-oxide-target/release/cargo-oxide"; do
    if [[ -x "$candidate" ]]; then
      CARGO_OXIDE_BIN="$candidate"
      break
    fi
  done
fi
if [[ -z "$CARGO_OXIDE_BIN" || ! -x "$CARGO_OXIDE_BIN" ]]; then
  echo "error: cargo-oxide binary not found" >&2
  echo "  Build it first: cd $CUDA_OXIDE_DIR && cargo build -p cargo-oxide --release" >&2
  exit 2
fi

if ! command -v llc-21 >/dev/null 2>&1; then
  echo "error: llc-21 not in PATH (install llvm-21 — see docs/setup.md)" >&2
  exit 2
fi

EXAMPLE_DIR="$CUDA_OXIDE_DIR/crates/rustc-codegen-cuda/examples/$EXAMPLE"
if [[ ! -d "$EXAMPLE_DIR" ]]; then
  echo "error: example not found at $EXAMPLE_DIR" >&2
  exit 2
fi

LL="$EXAMPLE_DIR/$EXAMPLE.ll"
PTX="$EXAMPLE_DIR/$EXAMPLE.ptx"
BIN="$EXAMPLE_DIR/target/release/$EXAMPLE"

echo "[1/3] cargo oxide build $EXAMPLE"
( cd "$CUDA_OXIDE_DIR" && "$CARGO_OXIDE_BIN" build "$EXAMPLE" ) >/dev/null

if [[ ! -f "$LL" ]]; then
  echo "error: $LL not generated by cargo oxide build" >&2
  exit 1
fi
if [[ ! -x "$BIN" ]]; then
  echo "error: $BIN not generated" >&2
  exit 1
fi

# Detect sm_80+ specific ops in IR; warn loudly if found
SM80_OPS_REGEX='(cp\.async|wgmma|tcgen05|tma\.|cluster\.)'
if grep -qE "$SM80_OPS_REGEX" "$LL"; then
  echo "WARNING: $EXAMPLE.ll contains sm_80+ specific ops:" >&2
  grep -nE "$SM80_OPS_REGEX" "$LL" | head -5 >&2
  echo "  $ARCH may not be able to JIT-load the resulting PTX." >&2
  echo "  Continuing anyway; expect CUDA_ERROR_INVALID_PTX (218) at runtime." >&2
fi

echo "[2/3] llc-21 --mcpu=$ARCH -mattr=$PTX_FEATURE  $LL"
llc-21 --mcpu="$ARCH" -mattr="$PTX_FEATURE" "$LL" -o "$PTX"
PTX_TARGET="$(grep -oE '\.target sm_[0-9]+' "$PTX" | head -1)"
echo "  PTX header: $PTX_TARGET"

if [[ "$NO_RUN" -eq 1 ]]; then
  echo "[3/3] --no-run specified"
  echo "  Binary: $BIN"
  echo "  PTX:    $PTX"
  exit 0
fi

echo "[3/3] exec $BIN"
cd "$EXAMPLE_DIR"
exec ./target/release/"$EXAMPLE"
